name: Arithma CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-backend:
    name: Rust Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
          
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install wasm-pack and update dependencies
        run: |
          cargo install wasm-pack
          cargo update -p wasm-bindgen-macro
          
      - name: Check formatting
        run: cargo fmt -- --check
        
      - name: Lint with clippy
        run: RUSTFLAGS="--allow=unexpected_cfgs" cargo clippy -- -D warnings
        
      - name: Build
        run: RUSTFLAGS="--allow=unexpected_cfgs" cargo build --verbose
        
      - name: Run tests
        run: RUSTFLAGS="--allow=unexpected_cfgs" cargo test --verbose
        
      - name: Build WebAssembly
        run: RUSTFLAGS="--allow=unexpected_cfgs" wasm-pack build --target web

  typescript-frontend:
    name: TypeScript Frontend
    runs-on: ubuntu-latest
    needs: [rust-backend] # Needs Rust backend to complete first for WASM files
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Install wasm-pack and update dependencies
        run: |
          cargo install wasm-pack
          cargo update -p wasm-bindgen-macro
        
      - name: Build WebAssembly
        run: RUSTFLAGS="--allow=unexpected_cfgs" wasm-pack build --target web
        
      - name: Copy WASM to frontend
        run: |
          mkdir -p frontend/public/pkg
          cp -r pkg/* frontend/public/pkg/
          mkdir -p frontend/node_modules/arithma
          cp -r pkg/* frontend/node_modules/arithma/
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Lint
        working-directory: ./frontend
        run: npm run lint
        
      - name: Type check
        working-directory: ./frontend
        run: npm run typecheck
        
      - name: Build
        working-directory: ./frontend
        run: npm run build:ci

  # This job ensures all tests pass in a fully integrated environment
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [rust-backend, typescript-frontend]
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Install wasm-pack and update dependencies
        run: |
          cargo install wasm-pack
          cargo update -p wasm-bindgen-macro
          
      - name: Build WebAssembly
        run: RUSTFLAGS="--allow=unexpected_cfgs" wasm-pack build --target web
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install frontend dependencies
        run: cd frontend && npm ci
        
      - name: Copy WASM build to frontend
        run: |
          mkdir -p frontend/public/pkg 
          cp -r pkg/* frontend/public/pkg/
          mkdir -p frontend/node_modules/arithma
          cp -r pkg/* frontend/node_modules/arithma/
        
      - name: Build frontend
        run: cd frontend && npm run build:ci
        
      # Add more integration tests here as needed